version: '3'

services:
  # Define a ngrok service
  ngrok:
    image: wernight/ngrok
    links:
      - splunk
    ports:
      - "4040:4040/tcp"
    command:
      - /bin/sh
      - -c
      - |
        ngrok http mist_flask:8088 --authtoken $NGROK_AUTH
#  receiver_configurator:
#    build:
#      context: ./receiver_configurator/
#      dockerfile: dockerfile
#    environment:
#      - MIST_API=$MIST_API
#      - MIST_ORG=$MIST_ORG
#      - MIST_SITE=$MIST_SITE
#    depends_on:
#      - ngrok
  #Define a splunk instance
  splunk:
    image: splunk/splunk:latest
    ports:
      - "8000:8000/tcp"
      - "8088:8088/tcp"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_LICENSE_URI=Free
      - SPLUNK_APPS_URL=https://splunkbase.splunk.com/app/3308/release/1.2.3/download
      - SPLUNKBASE_USERNAME=$SPLUNKBASE_USERNAME
      - SPLUNK_PASSWORD=$SPLUNK_PASSWORD


