from python:3.7
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV PYTHONPATH "${PYTHONPATH}:/usr/src/app"


ADD ./receiver_configurator/MistSystems.py /usr/src/app
ADD ./receiver_configurator/ngrok_wrapper.py /usr/src/app
ADD ./receiver_configurator/requirements.txt /usr/src/app

RUN pip install --no-cache-dir -r requirements.txt
ADD ./receiver_configurator/receiver_setup.py /usr/src/app/receiver_setup.py

CMD [ "python", "/usr/src/app/receiver_setup.py"]
