from python:3.7
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ENV PYTHONPATH "${PYTHONPATH}:/usr/src/app"


ADD ./MistSystems.py /usr/src/app
ADD ./ngrok_wrapper.py /usr/src/app
ADD ./requirements.txt /usr/src/app

RUN pip install --no-cache-dir -r requirements.txt
ADD ./receiver_setup.py /usr/src/app/receiver_setup.py

CMD [ "python", "-u", "/usr/src/app/receiver_setup.py"]
